[package]
name = "pomodoroom-desktop"
version = "1.0.5"
description = "Pomodoroom Desktop App"
authors = ["you"]
edition = "2021"

[[bin]]
name = "pomodoroom-desktop"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
pomodoroom-core = { path = "../crates/pomodoroom-core" }
tauri = { version = "2", features = ["tray-icon", "image-png", "macos-private-api"] }
tauri-plugin-opener = "2"
tauri-plugin-updater = "2"
tauri-plugin-process = "2"
tauri-plugin-notification = "2"
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
thiserror = { workspace = true }
keyring = "3"
reqwest = { version = "0.12", features = ["json"] }
base64 = "0.22"
getrandom = "0.2"
urlencoding = "2"
tokio = { version = "1", features = ["rt"] }
url = "2.5"
indexmap = "2"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = "z"
strip = true
panic = "abort"
